str = cellfun(@(x) num2str(x,2),num2cell(ss),'UniformOutput',false);

figure(10)
subplot(3,4,1)
boxplot(vTp,str)
xlabel('d0')
ylabel('seconds')
title('particle generation time')
subplot(3,4,2)
boxplot(vN,str)
xlabel('d0')
ylabel('#')
title('Number of points')
subplot(3,4,3)
boxplot(vR,str)
xlabel('d0')
ylabel('#')
title('Number of Iterations')

subplot(3,4,5)
boxplot(vTig,str)
xlabel('d0')
ylabel('seconds')
title('interpolation time global kernel')
subplot(3,4,6)
boxplot(abs(vIg),str)
set(gca,'YScale','log')
xlabel('d0')
ylabel('Integral')
title('integral approximation global kernel size')
subplot(3,4,7)
boxplot(abs(vEg),str)
set(gca,'YScale','log')
xlabel('d0')
ylabel('relative error')
title('Max Error with global kernel size')
subplot(3,4,8)
boxplot(abs(vEg1),str)
set(gca,'YScale','log')
xlabel('d0')
ylabel('relative error')
title('L1 Error with global kernel size')

subplot(3,4,9)
boxplot(vTil,str)
xlabel('d0')
ylabel('seconds')
title('interpolation time local kernel size')
subplot(3,4,10)
boxplot(abs(vIl),str)
set(gca,'YScale','log')
xlabel('d0')
ylabel('Integral')
title('integral approximation local kernel size')
subplot(3,4,11)
boxplot(abs(vEl),str)
set(gca,'YScale','log')
xlabel('d0')
ylabel('relative error')
title('Max Error with local kernel size')
subplot(3,4,12)
boxplot(abs(vEl1),str)
set(gca,'YScale','log')
xlabel('d0')
ylabel('relative error')
title('L1 Error with local kernel size')

myaa('publish')